# Generated by Django 4.2.2 on 2023-07-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        # migrations.RunSQL("""
        #     INSERT INTO store_collection (title)
        #     VALUES ('collection1')
        # ""","""
        #     DELETE FROM store_collection
        #     WHERE title = 'collection1'
        # """)
    ]
