# Generated by Django 4.2.2 on 2023-07-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featuredproduct',
            new_name='featured_product',
        ),
    ]
