# Generated by Django 4.2.2 on 2023-07-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_featuredproduct_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
